### ISSUE TITLE
Regarding XPV Project

### ISSUE THREAD

**Issue by Ravanger101** [Valensce/Valensce#2]
Hey Valensce,
Can you add me in: https://github.com/XPaVilion
So i can shift the XPV website here.
https://xpvilion.github.io/XPV/
Regards,
Aryan

**Comment by Valensce** [comment]
Sure thing! Btw would you mind if you could rename the repository to XPaVilion.github.io if you're transferring it directly so that it simplifies the final link to https://xpavilion.github.io/? Thanks Aryan~
