### ISSUE TITLE
Regarding emails

### ISSUE THREAD

**Issue by nasserkessas** [Valensce/Valensce#4]
Hello, @Valensce, I'd really appreciate it if you could take a look at your emails, I think that will clear a few things up. Sorry for posting this here, this is the only way I could think of getting a hold of you.

Regards,
Nasser Kessas

**Comment by Valensce** [comment]
Hey @nasserkessas, I was just checking my main email's spam box this morning to find some miscellaneous files and came across your message. I really appreciate your creativity in attempting to reach me this way, but more importantly, it worked!! I also just checked my subordinate email as per your request and yes, I can confirm that this is the person you're trying to reach. I'm sorry to hear that your discord account got hacked, and now I see why the messages have been so offensive. Thank you for letting me know or I would not have figured.

Warm regards,
Valensce

**Comment by nasserkessas** [comment]
:)
